In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type (arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [2]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [3]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2.reshape(2,5)



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[1,1,1,1,1]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  1  1  1  1]]
(3, 5)


In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
### Vector operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition:" , arr1+arr2)
print("Substraction:" , arr1-arr2)
print("Multiplication:" , arr1*arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]


In [10]:
### Universal Function

arr= np.array([2,3,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [21]:
### slicing and indexing

arr = np.array([[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]])
print("Array:\n",arr)


Array:
 [[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [22]:
arr[0][2]

np.int64(3)

In [25]:
arr[1:3,2:]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [26]:
print(arr)
print(arr[0:2,2:])

[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[3 4 5]
 [7 8 9]]


In [15]:
arr[0,0] = 100
print(arr)

[[100   2   3   4   5]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [27]:
arr[1:] = 99

print(arr)

[[ 1  2  3  4  5]
 [99 99 99 99 99]
 [99 99 99 99 99]]


In [17]:
### Statstical concepts - normalize

data = np.array([1,2,3,4,5])
mean = np.mean(data)
std_dev = np.std(data)

print(mean)
print(std_dev)

normalize_data = (data-mean)/std_dev
print("Normalized Data: \n",normalize_data)

3.0
1.4142135623730951
Normalized Data: 
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
